name = "lean-std"
version = "0.1.0"
defaultTargets = ["lean-std"]
testDriver = "«lean-std-tests»"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "LeanStd"

[[lean_exe]]
name = "lean-std"
root = "Main"

[[lean_lib]]
name = "Tests"
globs = ["Tests"]

[[lean_exe]]
name = "lean-std-tests"
root = "Tests.Main"
