name = "hale"
version = "0.1.0"
defaultTargets = ["hale"]
testDriver = "«hale-tests»"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "Hale"

[[lean_exe]]
name = "hale"
root = "Main"

[[lean_lib]]
name = "Tests"
globs = ["Tests"]

[[lean_exe]]
name = "hale-tests"
root = "Tests.Main"
